# Generated by Django 5.2.15 on 2026-06-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_add_due_date_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
                null=True,
            ),
        ),
    ]
